excurj/urls.py
from django.conf.urls import url, include
from excurj import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

# import registration.backends.simple.views

app_name='excurj'

urlpatterns=[
	url(r'^$', views.index, name='index'),
	url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.createprofile, name='signup'),
	url(r'^amp$', views.index_amp, name='index_amp'),
	url(r'^city/(?P<city_name_slug>[\w\-]+)/$', views.show_city, name='show_city'),
	url(r'^user/(?P<username>[\w\-]+)/$', views.show_profile, name='show_profile'),
	url(r'^search/$', views.search, name='search'),
	url(r'^createprofile/$', views.createprofile, name="createprofile"),
	url(r'^editprofile/$', views.editprofile, name="editprofile"),
	url(r'^editaccount/$', views.editaccount, name="editaccount"),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^createtrip/$', views.createtrip, name="createtrip"),
	url(r'^excursionrequest/(?P<username>[\w\-]+)/$', views.excursion_request, name="excursionrequest"),
	url(r'^offerexcursion/(?P<username>[\w\-]+)/$', views.offerexcursion, name="offerexcursion"),
	url(r'^feedback/$', views.feedback, name="feedback"),
	url(r'^thankyou/$', views.thankyou, name="thankyou"),
	url(r'^cities/$', views.cities_list, name="cities"),
	url(r'^confirmoffer/(?P<offerid>[\w\-]+)/$', views.confirmoffer, name="confirmoffer"),
	url(r'^acceptrequest/(?P<requestid>[\w\-]+)/$', views.acceptrequest, name="acceptrequest"),
	url(r'^leavereview_for_traveler/(?P<username>[\w\-]+)/$', views.leavereview_for_traveler, name="leavereview_for_traveler"),
	url(r'^leavereview_for_local/(?P<username>[\w\-]+)/$', views.leavereview_for_local, name="leavereview_for_local"),
	url(r'^eventdetails/(?P<cityslug>[\w\-]+)/(?P<eventid>[0-9]+)/$', views.eventdetails, name="eventdetails"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

excurj_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from excurj import views
# from registration.backends.simple.views import RegistrationView
from django.contrib.sitemaps.views import sitemap
from excurj.sitemap import CitySiteMap, ProfileSiteMap, ExcursionSiteMap

sitemaps = {
    'city' : CitySiteMap,
    'profile' : ProfileSiteMap,
    'excursion' : ExcursionSiteMap
}

# class MyRegistrationView(RegistrationView):
#     def get_success_url(self,user):
#         return('/createprofile/')

urlpatterns = [
	url(r'^', include('excurj.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'accounts/register/$', MyRegistrationView.as_view(), name='registraion_register'),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap')
]

excurj/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from excurj.models import City, UserProfile, RequestReference, Request, User, Excursion, Offer
from django.db.models import Count
from django.contrib.auth.models import User
import population_script
from django.db.models import Q
from excurj.forms import UserForm, UserProfileForm, EditAccountForm, EditProfileForm, \
 ExcursionRequestForm, CreateTripForm, OfferExcursionForm, FeedbackForm, LeaveReference_for_traveler, \
 LeaveReference_for_local
from datetime import datetime
from django.shortcuts import redirect
from django.core.exceptions import MultipleObjectsReturned
from django.core.mail import send_mail, BadHeaderError
from django.utils.safestring import mark_safe
import urllib.request, json
import requests
import dateutil.parser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from time import sleep
from django.utils.timezone import localtime
from django.contrib.auth import login, authenticate
from django.http import JsonResponse



def send_me_email(subject, message, to_email):
	"""Used so I receive emails when a new user signs up or does other things like send feedback"""
	try:
		send_mail(subject,  message, '', to_email)
	except BadHeaderError:
		return HttpResponse('Invalid header found.')


def index(request):
	context_dict={}

	# print("taaaaaaaaaaaaaaask is: " + str(fact.delay(20000).get(propagate=False)))

	#brings back top 6 cities with the highest number of users
	city_list = City.objects.annotate(user_count=Count('city__user')).order_by('-user_count')[:6]
	
	#The two references that are based on the front page
	#Currently featured references are from Requests (traveler asks local to take her out) 
		#and not offers (when local offers traveler to take him out)
	refs= RequestReference.objects.select_related('request') \
	.filter(traveler_fun=True,local_fun=True) \
	.order_by('-request__date')[:2]

	# refs = reversed(refs)
	
	context_dict['refs'] = refs

	context_dict['cities'] = city_list

	#bring back lat and lng for all cities to show them on the Google Maps
	lat_lng_dict=[]

	#Pull all cities to feature them on the Google Map with the number of users for each one
	all_cities = City.objects.select_related().annotate(count=Count('city__user'))

	#Loop thru cities and pull their name, lat, lng, slug and number of users
	for city in all_cities:
		if city.lat != None and city.name != '':
			lat_lng_entry = {
			'city_name' : city.name,
			'lat' : city.lat,
			'lng' : city.lng,
			'slug' : city.slug,
			'count' : city.count
			}

		#If the user only has one user then include her/his profile picture to feature it on the map marker pop up
		if city.count == 1:

			#A lonely user is called King as I might give royal titles to the first users of each city
			lat_lng_entry['king_pic'] = str(city.city.all()[0].prof_pic.url)

			#append city's lat and lng to the lat lng dictionary
			lat_lng_dict.append(lat_lng_entry)

		

	context_dict['all_cities'] =  mark_safe(lat_lng_dict)
	
	return render(request, 'excurj/index.html', context_dict)

def index_amp(request):
	context_dict={}

	# print("taaaaaaaaaaaaaaask is: " + str(fact.delay(20000).get(propagate=False)))

	#brings back top 6 cities with the highest number of users
	city_list = City.objects.annotate(user_count=Count('city__user')).order_by('-user_count')[:6]
	
	#The two references that are based on the front page
	#Currently featured references are from Requests (traveler asks local to take her out) 
		#and not offers (when local offers traveler to take him out)
	refs= RequestReference.objects.select_related('request') \
	.filter(traveler_fun=True,local_fun=True) \
	.order_by('-request__date')[:2]

	# refs = reversed(refs)
	
	context_dict['refs'] = refs

	context_dict['cities'] = city_list

	#bring back lat and lng for all cities to show them on the Google Maps
	# lat_lng_dict=[]

	# #Pull all cities to feature them on the Google Map with the number of users for each one
	# all_cities = City.objects.select_related().annotate(count=Count('city__user'))

	# #Loop thru cities and pull their name, lat, lng, slug and number of users
	# for city in all_cities:
	# 	lat_lng_entry = {
	# 	'city_name' : city.name,
	# 	'lat' : city.lat,
	# 	'lng' : city.lng,
	# 	'slug' : city.slug,
	# 	'count' : city.count
	# 	}

	# 	#If the user only has one user then include her/his profile picture to feature it on the map marker pop up
	# 	if city.count == 1:

	# 		#A lonely user is called King as I might give royal titles to the first users of each city
	# 		lat_lng_entry['king_pic'] = str(city.city.all()[0].prof_pic.url)

	# 	#append city's lat and lng to the lat lng dictionary
	# 	lat_lng_dict.append(lat_lng_entry)

		

	# context_dict['all_cities'] =  mark_safe(lat_lng_dict)
	
	return render(request, 'excurj/index_amp.html', context_dict)


def cities_list(request):
	context_dict={}

	#brings back top all cities with the highest number of users
	city_list = City.objects.annotate(user_count=Count('city__user')).order_by('-user_count')

	page = request.GET.get('page', 1)

	searched_query = request.GET.get('city-search', 'nothing')

	print("PAIGE IS "  + str(request))
	paginator = Paginator(city_list, 6)

	try:
		# sleep(2)
		cities = paginator.page(page)
	except PageNotAnInteger:
		cities = paginator.page(1)
	except EmptyPage:
		cities = paginator.page(paginator.num_pages)
	except:
		pass

	context_dict['cities'] = cities
	context_dict['searched_query'] = searched_query
	print(str(context_dict))
	
	
	return render(request, 'excurj/cities.html', context_dict)


def get_perma_fb_token():
	token = get_json_raw("https://graph.facebook.com/oauth/access_token?client_id=262023620939242&client_secret=13a20efc5cb8245237e8a8d08118abe1&grant_type=client_credentials")

def get_json_raw(url):
	"""takes facebook graph url and returns raw json"""
	response = requests.get(url)
	jsondata = json.loads(response.text)
	
	return jsondata

def pull_events(city):
	events=[]
	# url = 'https://graph.facebook.com/search?q=%s&type=event&access_token=EAADuTyDZATeoBAEO0VFZCZCROVUmhAdqE8ZCXFpQLqh4F3KRZCL9EIJ3N9MJZA4AUcVrNCJg077Oh80XJiyWwbLLmJiN7dFnSxm1OCm04ZCbuICDNvwlLMDhbUv3iYOzdEBPBKcZBSLUuQlyhZCPxeqsfhDscYQuIMGhZBq2EZCt0D4jQZDZD&token_type=bearer' % city.name.replace(' ', '')
	url = 'https://www.eventbriteapi.com/v3/events/search?token=6HXJMYZIFBDCKGFA5C6E&q=%s&sort_by=date' % city.name.replace(' ', '')
	events_json = get_json_raw(url)

	# print(events_json)

	# try:
	# # If no events were returned, try using the first level of the city name as query (Amman instead of Amman, Jordam)
	# 	if len(events_json['events']) == 0:
	# 		try_differeny_city_name = city.name.split(',');
	# 		try_differeny_city_name = try_differeny_city_name[0] + ',' + try_differeny_city_name[len(try_differeny_city_name) -1]

			
	# 		#PULL LOCAL EVENTS
	# 		url = 'https://graph.facebook.com/search?q=%s&type=event&access_token=EAADuTyDZATeoBAEO0VFZCZCROVUmhAdqE8ZCXFpQLqh4F3KRZCL9EIJ3N9MJZA4AUcVrNCJg077Oh80XJiyWwbLLmJiN7dFnSxm1OCm04ZCbuICDNvwlLMDhbUv3iYOzdEBPBKcZBSLUuQlyhZCPxeqsfhDscYQuIMGhZBq2EZCt0D4jQZDZD&token_type=bearer' % try_differeny_city_name.replace(' ', '')
			
	# 		events_json = get_json_raw(url)
	# 		print("WHYYYY" + events_json)

	# except Exception:
	# 	pass


		
		

	#Loop thru events and send list of events
	for event in events_json['events'][:6]:

		# pull event cover photo
		venue_url = 'https://www.eventbriteapi.com/v3/venues/{0}?token=6HXJMYZIFBDCKGFA5C6E'.format(event['venue_id'])
		
		event_photo_json = get_json_raw(venue_url)
		if 'name' in event_photo_json:
			event['venue_name'] = event_photo_json['name']
		if 'address' in event_photo_json:
			event['venue_address'] = event_photo_json['address']['localized_address_display']

		if 'latitude' in event_photo_json:
			event['lat'] = event_photo_json['latitude']

		if 'longitude' in event_photo_json:
			event['lng'] = event_photo_json['longitude']

		# Pull venue image
		# venue_photo_url = 'https://maps.googleapis.com/maps/api/place/textsearch/json?query={0}&location={1},{2}&radius=10000&key=AIzaSyAC9SSvIEbSOt7ocozi4AxBoFqOz7ZX2Wc'.format(event['venue_address'], event_photo_json['longitude'], event_photo_json['latitude'])
		# event_photo_json = get_json_raw(venue_photo_url)
		# print('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'+str(event_photo_json['results']))
		# if 'type' in event_photo_json:
		# 	event['type'] = event_photo_json['type']
		
		#append event to events list
		events.append(event)
	
	return events


def pull_city(city_name_slug):
	try:

		#Try pull the City object from the passed slug
		city = City.objects.get(slug=city_name_slug)

	#Error message will be shown if the city being searched does not exist
	except City.DoesNotExist:
		context_dict['city']=None


	#If more than one city returned (for whatever reason) then return the first one
	except City.MultipleObjectsReturned:
		city = City.objects.filter(slug=city_name_slug)[0]

	return city

def show_city(request, city_name_slug):
	""" Django View to show city profile page """

	context_dict={}

	try:

		#Try pull the City object from the passed slug
		city = pull_city(city_name_slug)
		
		#Pull associated user profiles to feature them under the "Locals" tab
		city_locals_profiles = UserProfile.objects.filter(city=city)

		#Pull trips to this city to feature them under "People coming to this city soon"
		excursions = Excursion.objects.filter(city=city)

		context_dict['city']=city
		context_dict['city_locals_profiles']=city_locals_profiles
		context_dict['excursions'] = excursions

	except UserProfile.DoesNotExist:
		context_dict['city_locals_profiles']=None

	except Excursion.DoesNotExist:
		context_dict['excursions'] = None
	except Exception:
		pass

	# Pull city events from the Facebook Graph
	events = pull_events(city)

	context_dict['events'] = events

	return render(request, 'excurj/city.html', context_dict)

def eventdetails(request, cityslug, eventid):

	city = pull_city(cityslug)

templates/excurj/base_no_amp.html
<!DOCTYPE html>

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
<html lang="en">
  <head>
    <meta name="google-site-verification" content="d7IKi6SBNmc0FzbEXaNUnROytKQhPrZkzwjW1SbTtY8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href=" {% static 'images/favicon-32x32.png' %} ">


    {% block scripts_block %}
    {% endblock %}

    <!-- <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet"> -->

    {% block desc_block %}
      <meta name="description" content="excurj. is a community where people show visitors around their cities to make new inter-cultural friendships! Meet interesting locals on your next trip | Go on free excurions | Learn about cool local events | Meet travel mates and more! (FREE)">
    {% endblock %}

    {% block kw_block %}
      <meta name="keywords" content="Travel, travel mates, excursions, europe, asia, australia, friends, fun, genuine travel experience, culture, cultural exchange, inter-cultural relationships, tolerance, travel, travel blogging, excurj. is a community where people show visitors around their cities to make new inter-cultural friendships! Meet interesting locals on your next trip | Go on free excurions | Learn about cool local events | Meet travel mates and more! (FREE)">
    {% endblock %}
    <meta name="author" content="Seif Elmughrabi">


    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '1920864801525488'); // Insert your pixel ID here.
    fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=1920864801525488&ev=PageView&noscript=1"
    /></noscript>
    <!-- DO NOT MODIFY -->
    <!-- End Facebook Pixel Code -->



    <title>

    {% block title_block %}
      excurj | Make Friendships Via Travel 
    {% endblock %}

    </title>

    <!-- Bootstrap CSS and CSS-->
    <link href="{% static 'css/bootstrap.min.css'%} " rel="stylesheet">
    <link rel="stylesheet" type="text/css" href=" {% static 'css/style.css' %} ">
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <!-- <link rel="stylesheet" type="text/css" href=" {% static 'css/animate.css' %} "> -->
    
    


    <!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAali5z1ZHUooZzMz7GP_sqMYDVpN-PQl8"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<!-- Google Analytics script -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-58047753-2', 'auto');
  ga('send', 'pageview');
</script>
    
    {% block extra_style %}
      
    {% endblock %}



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    


    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "WebSite",
        "url": "https://www.excurj.com/",
        
        "potentialAction": {
        "@type": "SearchAction",
        "target": "https://www.excurj.com/search/?city-search={search_term_string}",
        "query-input": "required name=search_term_string"
        }
      }
    </script>
    <script async custom-element="amp-install-serviceworker" src="https://cdn.ampproject.org/v0/amp-install-serviceworker-0.1.js"></script>
    <link rel="manifest" href="/static/manifest.json">
  </head>
  <body>
    <amp-install-serviceworker src="https://www.excurj.com/serviceworker.js" layout="nodisplay"></amp-install-serviceworker>
    <form action=" {% url 'excurj:feedback' %} ">
        <button title="Contact Us, We Love Your feedback!" id="feedback" class="btn btn-lg btn-primary" name="feedback">
        <span class="glyphicon glyphicon-send" style="padding-right: 10px;"></span>  FEEDBACK
      </button>
    </form>

    <div>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <!-- logo -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href=" {% url 'excurj:index' %} " title="excurj | Make New Friendships Via Travel"><img src=" {% static 'images/logo.png' %} " alt="Excurj logo"></a>       
          </div>

          <!--menu items-->
          <div class="collapse navbar-collapse " id="mainNavBar">
            <ul class="nav navbar-nav ">
              <li><a href="{% url 'excurj:index' %}#how-it-works" title="How it works">How it Works</a></li>
              <li><a href=" {% url 'excurj:index' %}#superstars" title="Superstars">Super Stars</a></li>
              <li><a href=" {% url 'excurj:index' %}#popularcities " title="Popular cities">Popular Cities</a></li>
              <li><a href=" {% url 'excurj:cities' %} " title="All cities">All Cities</a></li>
              <li><a href=" {% url 'excurj:index' %}#insta " title="Instagram feed (#excurj)">Insta Feed</a></li>
              <li><a href=" {% url 'excurj:index' %}#map_canvas " title="excurj Map">Map</a></li>
              {% if request.user.is_authenticated %}
                <li class=" no_desktop"><a href=" {% url 'excurj:dashboard' %} ">My Dashboard</a></li>
                <li class=" no_desktop"><a href="{% url 'excurj:show_profile' request.user.username %}">My Profile</a></li>
                <li class=" no_desktop"><a class="no_desktop" href="">Account</a></li>
                <li class=" no_desktop"><a href="{% url 'excurj:logout' %}?next=/"> logout</a></li>
              {% endif %}
            </ul>

            <form class="navbar-form navbar-right no_mobile" action=" {% url 'excurj:search' %} ">
                <div class="form-group no_mobile">
                    <input type="text" name="q" class="form-control no_mobile" placeholder="Search people..." id="topsearchbox">
                </div>
                  <button type="submit" class="btn btn-default no_mobile"><span class="glyphicon glyphicon-search"></span></button>
            </form> 

            <ul class="nav navbar-nav navbar-right">

            {% if not request.user.is_authenticated %}

              <li><a href=" {% url 'excurj:login' %} ">LOG IN</a></li>
              <li class="animated infinite tada"><a href="{% url 'excurj:createprofile' %}">JOIN</a></li>

            {% else %}

            <li style="position: relative; background-color: transparent;" id="prof_li">
              <a href="" style="display: inline;" class="no_mobile"> 
                <img src=" {{request.user.profile.prof_pic.url}} " height="49px" width="49px" class="img-circle no_mobile"> 
                <span class="caret no_mobile"></span> 
              </a>
            </li>

            <div id="prof_dropdown">
              <li class="dropli no_mobile"><a class="no_mobile" href="{% url 'excurj:dashboard' %}">My Dashboard</a></li>
              <li class="dropli no_mobile"><a class="no_mobile" href="{% url 'excurj:show_profile' request.user.username %}">My Profile</a></li>
              <li class="dropli no_mobile"><a class="no_mobile" href="{% url 'excurj:editaccount' %}">Account</a></li>
              <li class="dropli no_mobile"><a class="no_mobile" href="{% url 'excurj:logout' %}?next=/"> logout</a></li>
            </div>

            {% endif %}

            </ul>
            
          </div>
        </div>
      </nav>

      <div>
        {% block body_block %}
        <p class="lead">This page is undergoing maintenance, it'll be up in a giffy :)</p>
        {% endblock %}
      </div>

    

    <footer style="text-align: center;max-height: 100px;"> 
      
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-xs-12">
            <a title="excurj logo" href=" {% url 'excurj:index' %} " class="">
              <img src=" {% static 'images/logo.png' %} " class="" alt="excurj logo">
            </a>
          </div>

          <div class="col-md-4 col-xs-12">
            <div class="call-to-action">Connect with us</div>
            <a href='#'><i class="fa fa-instagram fa-3x fa-fw"></i></a>
            <a href='#'><i class="fa fa-facebook fa-3x fa-fw"></i></a>
            <a href='#'><i class="fa fa-twitter fa-3x fa-fw"></i></a>
            <a href='#'><i class="fa fa-flickr fa-3x fa-fw"></i></a>
          </div>

          
        </div>

        <div class="row">
          <div class="col-lg-4">
            <ul class="footer-links">
                <li> <a href="">ABOUT</a> </li>
                <li> <a href="">SAFETY</a> </li>
                <li> <a href="">SUPPORT</a> </li>
                <li> <a href="">BLOG</a> </li>
            </ul>
          </div>

          <div class="col-lg-4">
            <div class="copyrights">

              <p class="" >
                Copyrights 2018 by excurj.com. Made with 100% recycled pixels.
              </p>

            </div>
          </div>

          
        </div>
        
      </div> 
      
    </footer>

  </body>
</html>

templates/excurj/createtrip.html
{% extends 'excurj/base_no_amp.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title_block %}
	Create Trip Form | excurj.
{% endblock %}

{% block body_block %}

<div class="col-sm-6 col-sm-offset-3" style="margin-top: 100px;margin-bottom: 100px">	
<h1>Create Your Next Adventure!</h1>
	<form method="post" action="?next=/dashboard/" enctype="multipart/form-data">
                {% csrf_token %}
              
        {{ create_trip_form|crispy }}

	    <input type="submit" value="Submit" class="btn btn-primary btn-lg "/>

    </form>    	

</div>
{% endblock %}

templates/excurj/editprofile.html
{% extends 'excurj/base_no_amp.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title_block %}
	Update Your Profile
{% endblock %}

{% block body_block %}

<div class="col-sm-6 col-sm-offset-3" style="margin-top: 100px;margin-bottom: 100px">	
<h1>Update Your Profile</h1>
	<form method="post" action="?next=/" enctype="multipart/form-data">
        {% csrf_token %}
    	{{ edit_profile_form|crispy }}

        <input type="submit" value="Submit" class="btn btn-primary btn-lg "/>
    </form>    	

</div>

<script src="{% static 'js/autocomplete.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYfS_V4jHXS_jVYa1k2w9VY52r0pMrL8g&callback=initMap&libraries=places"></script>
{% endblock %}

templates/excurj/leavereview_for_local.html
{% extends 'excurj/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block title_block %}
	Request an Excusrion from a local
{% endblock %}

{% block body_block %}

<div class="col-sm-6 col-sm-offset-3" style="margin-top: 100px;margin-bottom: 100px">	
<h1>Leave <strong>{{referenced_person_name}}</strong> a reference here!</h1>
	<form method="post" action="?next=/" enctype="multipart/form-data">
                {% csrf_token %}
              
        {{ leavereview_for_local_form|crispy }}

	    <input type="submit" value="Submit" class="btn btn-primary btn-lg "/>

    </form>    	

</div>


{% endblock %}

templates/excurj/search.html
{% extends 'excurj/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Search Results
{% endblock %}

{% block body_block %}
	<div style="margin-top: 70px;">	

	<h1>People Search results</h1>

	{% if users %}
	<h2>We found these people based on your query</h2>
		{% for user in users %}
		<ul>
			<li>  <a href=" {% url 'excurj:show_profile' user.username %} ">{{ user.first_name }}  {{ user.last_name }}</a>  </li>
		</ul>
		{% endfor %}

	{% else %}
	<p>No users were found based on your query :( you can search by:</p>
	<ul>
		<li>First name</li>
		<li>Last name</li>
		<li>username</li>
		<li>email</li>
		<li>user's home city</li>
	</ul>
	{% endif %}

	</div>
{% endblock %}